name: CI-UAT
#on: [push, pull_request]
on: 
 workflow_dispatch:
  inputs:
     test_suite_names:
      description: 'Test Suites'
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
          
        - name: Test
          run: npm run test:local.uat
        - uses: actions/upload-artifact@v1
          continue-on-error: true
          if: failure()
          with:
            name: logs
            path: logs

 
        
